# Generated by Django 4.1.7 on 2023-02-28 20:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holedescription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nationalroute', models.CharField(max_length=50)),
                ('pkbegin', models.IntegerField()),
                ('pkend', models.IntegerField()),
                ('width', models.IntegerField()),
                ('holelevel', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'db_table': 'holedescription',
            },
        ),
        migrations.CreateModel(
            name='Holelevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('thickness', models.IntegerField()),
            ],
            options={
                'db_table': 'holelevel',
            },
        ),
        migrations.CreateModel(
            name='MadagascarRoad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('linkno', models.CharField(max_length=20)),
                ('roadno', models.CharField(max_length=20)),
                ('start_km', models.BigIntegerField()),
                ('end_km', models.BigIntegerField()),
                ('lenghtkm', models.FloatField()),
                ('startdesc', models.CharField(max_length=100)),
                ('enddesc', models.CharField(max_length=100)),
                ('classe', models.CharField(db_column='class', default='', max_length=50)),
                ('regions', models.CharField(max_length=50)),
                ('width', models.FloatField()),
                ('lanes', models.IntegerField()),
                ('surftype', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=30)),
                ('aadt', models.BigIntegerField()),
                ('iso3', models.CharField(max_length=50)),
                ('aicd_reg', models.IntegerField()),
                ('p082806', models.IntegerField()),
                ('p073689', models.IntegerField()),
            ],
            options={
                'db_table': 'madagascarroad',
            },
        ),
        migrations.CreateModel(
            name='Nationalroute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('beginroute', models.CharField(max_length=50)),
                ('endroute', models.CharField(max_length=50)),
                ('beginpk', models.IntegerField()),
                ('endpk', models.IntegerField()),
            ],
            options={
                'db_table': 'nationalroute',
            },
        ),
        migrations.CreateModel(
            name='Route_fusion',
            fields=[
                ('roadno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start_km', models.FloatField()),
                ('end_km', models.FloatField()),
                ('longueur', models.FloatField()),
                ('largeur', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'db_table': 'route_fusion',
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('linkno', models.CharField(max_length=20)),
                ('roadno', models.CharField(max_length=20)),
                ('start_km', models.FloatField()),
                ('end_km', models.FloatField()),
                ('lengthkm', models.FloatField()),
                ('startdesc', models.CharField(max_length=100)),
                ('enddesc', models.CharField(max_length=100)),
                ('classe', models.CharField(db_column='class', default='', max_length=50)),
                ('regions', models.CharField(max_length=50)),
                ('width', models.FloatField()),
                ('lanes', models.IntegerField()),
                ('surftype', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=30)),
                ('aadt', models.FloatField()),
                ('iso3', models.CharField(max_length=50)),
                ('aicd_reg', models.IntegerField()),
                ('p082806', models.IntegerField()),
                ('p073689', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Workmanship',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=50)),
                ('duration', models.FloatField()),
            ],
            options={
                'db_table': 'workmanship',
            },
        ),
    ]
